### ISSUE TITLE
Split Card Name it separate Columns

### ISSUE THREAD

**Issue by gaddlord** [gaddlord/mtg.studio#368]
Kevin Hollenshead:
Move the descriptors of cards (the collector #, [Token], [Prerelease], etc.) out of the card description and into their own fields in the database. I think this will help you with any compatibility issues going forward and (I would hope) with pricing updates. Same for the collector number (e.g. 364 not 364 M).

**Comment by gaddlord** [comment]
Gad:
You suggestion makes sense - we can add
* Model - the pure card name
* Sub Set
* Release Date
* Language
* Version
as separate columns.

This way one can decide to see the Model Name - "Terror" or the Card Name - "Terror [FR] (2)".

**Comment by texasaggie1994** [comment]
In addition, I believe this will improve your interoperability on pricing lookups.

**Comment by gaddlord** [comment]
Will be available in version 4.0 where we have the following columns:
Card - the full name of the card with all SubSet, Language, Foil, Version facets
Name in Deck - the card name as printed on the English version of the card and as usually listed in Deck Sheets
Name as Printed - original card name as typed on the card.

<img width="908" alt="image" src="https://user-images.githubusercontent.com/279005/233685596-53095850-d9c6-4d70-817b-226b69298deb.png">

For the collector number we decided to keep as printed on the card but sorting is performed only on the numeric part.
