### ISSUE TITLE
Missing Cards from Streets of New Capenna Commander (NCC)

### ISSUE THREAD

**Issue by texasaggie1994** [gaddlord/mtg.studio#380]
Noticed the following cards missing from the database for the NCC set while I was trying to enter them - #'s 86 through 92.

![image](https://user-images.githubusercontent.com/9547446/178157035-d6ea5084-1200-4f02-b11f-727c268fd8b8.png)

**Comment by gaddlord** [comment]
Those will be present in the next version 3.164. Send email to gaddlord @ mtgstudio . com in case you need the db sooner.
