### ISSUE TITLE
Excel export, file extension misspelled

### ISSUE THREAD

**Issue by LemonyFresh90** [gaddlord/mtg.studio#381]
When I exported my collection to excel, the file format came out as ".xslx"  which was not recognized.  If you were to save a document in excel and look at the available formats, ".xslx" was not an option.  My only guess is the extension was misspelled for exports.  When I changed the format to ".xlsx", Windows recognized it and opened successfully.

Edit:

doing it on another attempt, the file extension looks correct in the 'save as' window, until I click save again to confirm.  The file comes out as ".xslx", even in the Type column it says XSLX File.

**Comment by gaddlord** [comment]
Fixed in forthcoming MTG Studio version 3.165.
