### ISSUE TITLE
missing cards from modern horizons 2 

### ISSUE THREAD

**Issue by justmarriedagain** [gaddlord/mtg.studio#389]
none of the basic land cards are on the modern horizons 2 list

**Comment by gaddlord** [comment]
Indeed. I have added those 10 lands to forthcoming MTG Studio 3.166

**Comment by justmarriedagain** [comment]
hello again. i have a few more cards that arent in the database. four that are from commander: kamigawa neon dynasty which are threefold signal, maestros confluence, smuggler's buggy and syrix, carrier of the flame. also one from dominaria united which is serra redeemer. thanks
    On Sunday, July 31, 2022 at 03:25:10 PM CDT, Gad D Lord ***@***.***> wrote:  
 
 


Indeed. I have added those 10 lands to forthcoming MTG Studio 3.166

**Comment by gaddlord** [comment]
Can it be that you are mistaken? Those cards
* Threefold signal
* Maestros confluence
* Smuggler's buggy
* Syrix, carrier of the flame
Are available in New Capenna: Commander (not Commander: Kamigawa Neon Dynasty).

Serra Redeemer from Dominaria United is avalable.

**Comment by justmarriedagain** [comment]
you are correct but they all have just a promo version in the database, not the plain version. i guess i should sleep more. thank you
    On Thursday, December 22, 2022 at 08:33:20 AM CST, Ivelin Nikolaev ***@***.***> wrote:  
 
 


Can it be that you are mistaken? Those cards
   
   - Threefold signal
   - Maestros confluence
   - Smuggler's buggy
   - Syrix, carrier of the flame   
Are available in New Capenna: Commander (not Commander: Kamigawa Neon Dynasty).

Serra Redeemer from Dominaria United is avalable.
