### ISSUE TITLE
Missing Card(s): Dominaria United

### ISSUE THREAD

**Issue by texasaggie1994** [gaddlord/mtg.studio#401]
- #282 - Serra Redeemer

**Comment by gaddlord** [comment]
I do see the card in the latest version. Perhaps you have some filters applied?
![image](https://user-images.githubusercontent.com/279005/208771694-f73ff1b6-6a3d-46df-9318-a6ed11e30cd8.png)

**Comment by texasaggie1994** [comment]
That is the alternate art version. #282 (the normal version) doesn't exist still.

**Comment by texasaggie1994** [comment]
![image](https://user-images.githubusercontent.com/9547446/208784720-163bb17a-70e3-479b-9c0e-776b0ad6d7bd.png)

**Comment by gaddlord** [comment]
Checking...

**Comment by gaddlord** [comment]
https://scryfall.com/card/dmu/282/serra-redeemer is added in forthcoming version 3.182
