### ISSUE TITLE
[Missing Card] 

### ISSUE THREAD

**Issue by Artheos40** [gaddlord/mtg.studio#442]
Fill in all fields or at least the Card Image Link pointing to a scanned copy of the card of the exact edition with high quality.

Supernatural Stamina 
Double Master 2020

**Comment by gaddlord** [comment]
I do see the card. Perhaps you have applied some filters?
![image](https://user-images.githubusercontent.com/279005/208771470-de3ddddc-25c7-4b4e-bf77-541670186bb5.png)

**Comment by Artheos40** [comment]
the one you see is for double masters 2022 not the previous one (2XM) so its missing
