### ISSUE TITLE
mtgstudio.com website down (causing errors retrieving art and card info)

### ISSUE THREAD

**Issue by texasaggie1994** [gaddlord/mtg.studio#466]
The site is down as of Dec 20th. This is causing the app to throw an error when retrieving card artwork.

**Comment by gaddlord** [comment]
We have been migrating:
http://mtgstudio.com, https://mtgstudio.com, http://www.mtgstudio.com, https://www.mtgstudio.com,
http://makedeck.com, https://makedeck.com, http://www.makedeck.com, https://www.makedeck.com,
http://palmroot.com, https://palmroot.com, http://www.palmroot.com, https://www.palmroot.com

to https://mtg.studio

The migration is complete now and all of the above should open fine including fetching the card art.
