### ISSUE TITLE
[bad card #] in guilds of ravnica set

### ISSUE THREAD

**Issue by Artheos40** [gaddlord/mtg.studio#487]
card numbers in guilds of ravnica are wrong, 
#221 to #230 are wrong. in that set, only those are wrong. I am curently building my database, so i pass by most cards. that'S how i found out;
instead they are numbered #20a to #30a 
here are as should be : 
221 Assure/Assemble
222 Connive/Concoct
223 Discovery/Dispersal
224 Expansion/Explosion
225 Find/Finality
226 Flower/Flourish
227 Integrity/Intervention
228 Invert/Invent
229 Response/Ressurgence
230 Status/Statue

thanks

**Comment by gaddlord** [comment]
Fixed in next version 3.179. Thanks for reproting.

<img width="343" alt="image" src="https://user-images.githubusercontent.com/279005/219963752-48fc275b-b043-4b8e-b9ef-e585c602060f.png">
