### ISSUE TITLE
[bad card #] command the dreadhorde

### ISSUE THREAD

**Issue by Artheos40** [gaddlord/mtg.studio#488]
name : Command the dreadhorde
set : War of the Spark
Set code : WAR
card # 82s

after sorting by number, it doesnt show where the number should be.
it sorts as if there was a space just before the numbers as it sorts before 001.

or its just a sorting but but shoudlnt be one. thanks

![IMG_20230221_165432](https://user-images.githubusercontent.com/119977998/220470359-5cc80309-9aad-4a0b-88e5-afa70210a65a.jpg)

**Comment by gaddlord** [comment]
Fixed in forthcoming 3.182 to have the collector number "082/264 R Spotlight: Act III" instead.
