### ISSUE TITLE
Missing Card: Mite Overseer - ONE

### ISSUE THREAD

**Issue by texasaggie1994** [gaddlord/mtg.studio#491]
Note the extended/showcase version #409 is there but #404 is missing in the database. I suspect it might be due to the same name in the database (based on cards around it)

Fill in all fields or at least the Card Image Link pointing to a scanned copy of the card of the exact edition with high quality.

Sample
Card Image Link: https://scryfall.com/card/one/404/mite-overseer
Name: Mite Overseer
Foreign Name: 
Set: Phyrexia: All Will Be One (ONE) 
Sub-Set: 
Version: no version
Language: English
Foil: No
Card Type: Creature - Phyrexian Soldier
Power: 4
Toughness: 2
Rules: First strike

As long as it’s your turn, creature tokens you control get +1/+0 and have first strike.
Flavor:
Artist: Nestor Ossandon Leal
Collector No: 404
Color: White
Released: ?
Notes:

———
Upvote my request be pressing 👍 from the 😊 menu.

**Comment by gaddlord** [comment]
I see it available as "Mite Overseer [Jumpstart]" with collector no "404 R" under "Phyrexia: All Will Be One" (subset Jumpstart)

<img width="829" alt="image" src="https://user-images.githubusercontent.com/279005/236890962-6d85f185-24e0-499d-af11-37fe9a959b31.png">
