### ISSUE TITLE
Phyrexia All Will Be One missing

### ISSUE THREAD

**Issue by drwombat** [gaddlord/mtg.studio#494]
Just installed 3.179 and all of my catalogued cards for ONE have been removed and no longer exist even in the card list. What the heck happened? Is there any way to restore the database from before so I don't have to manually re-add all of my ONE cards to the collection? Please fix asap.

**Comment by gaddlord** [comment]
Can you please share the deck you are testing with at gad@mtg.studio?

**Comment by drwombat** [comment]
Not a deck. The entire program no longer includes All Will Be One.

**Comment by drwombat** [comment]
See attached

On 03/28/2023 12:56, Ivelin Nikolaev wrote:

> Can you please share the deck you are testing with at ***@***.***? 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/gaddlord/mtg.studio/issues/494#issuecomment-1487283665
[2]

**Comment by drwombat** [comment]
https://i.imgur.com/qlH9kg1.png

**Comment by drwombat** [comment]
https://i.imgur.com/OAk5uOI.png

**Comment by gaddlord** [comment]
Understood. Seems like the database had been reverted to Version 3.177 state. Likely a human erro - still investigating. 
As a temp workaround please install version 3.178 instead which has ONE.
I will work towards adding all cards from 3.178 and 3.179 back in the nexy 3.180 version.

**Comment by drwombat** [comment]
ok thank you - where can I find the prior version to download?? The website only offers 3.179

**Comment by gaddlord** [comment]
Confirmed - it is a human error. I will need to reenter all changes done in 3.179 only and replublish.

You can download the older and working version from https://s3.amazonaws.com/mtg.studio/stable/MTG_Studio_3.178.exe

**Comment by drwombat** [comment]
Cool thank you and 3.178 works just fine. 
How will users know once the repaired 3.179 is published? Obviously right now the app is telling me to update and I am just ignoring that bc of the error.

**Comment by gaddlord** [comment]
Version 3.182 (the latest so far) has it all.
