### ISSUE TITLE
bad card numbers GRN set undone

### ISSUE THREAD

**Issue by Artheos40** [gaddlord/mtg.studio#497]
somecard numbers in guilds of ravnica are wrong,
https://github.com/gaddlord/mtg.studio/issues/221 to https://github.com/gaddlord/mtg.studio/issues/230 are wrong. in that set, only those are wrong. I am curently building my database, so i pass by most cards. that'S how i found out;
instead they are numbered #20a to #30a
here are as should be :
221 Assure/Assemble
222 Connive/Concoct
223 Discovery/Dispersal
224 Expansion/Explosion
225 Find/Finality
226 Flower/Flourish
227 Integrity/Intervention
228 Invert/Invent
229 Response/Ressurgence
230 Status/Statue

[update]
were supposed to be changed in 3.179 but i'm guessing got undone because of the rollback to 3.178 and the skip to 3.180.
added a screenshot to show what is meant

thanks

![Capture d’écran 2023-04-20 180537 GRN](https://user-images.githubusercontent.com/119977998/233497359-a09ce10e-c547-4d9a-871b-9b5140c9e806.png)

**Comment by gaddlord** [comment]
Fixed in forthcoming 3.182
