### ISSUE TITLE
Add MOM set

### ISSUE THREAD

**Issue by gaddlord** [gaddlord/mtg.studio#499]
- run all DB Integrity check procedures from the database

**Comment by drwombat** [comment]
Hi I see on https://github.com/gaddlord/mtg.studio/wiki/Version-History that the MOM set has been added. But the program doesn't recognize there is an upgrade available. Where can I download the latest version 3.181?

**Comment by gaddlord** [comment]
Hello,

You can always install the latest version from https://mtg.studio <https://mtg.studio> 

Which is your current version so I can try to troubleshoot the auto-update?

Gad D Lord

On Sun, Apr 30, 2023 at 12:03 AM drwombat ***@***.*** ***@***.***> > wrote:

Hi I see on https://github.com/gaddlord/mtg.studio/wiki/Version-History <https://github.com/gaddlord/mtg.studio/wiki/Version-History> that the MOM set has been added. But the program doesn't recognize there is an upgrade available. Where can I download the latest version 3.181?

**Comment by drwombat** [comment]
It worked the next day thanks!
  

  

  

  
  
  
  
  
>

**Comment by gaddlord** [comment]
Reported as resolved.
