### ISSUE TITLE
Add MAT

### ISSUE THREAD

**Issue by skarsol** [gaddlord/mtg.studio#509]
https://scryfall.com/sets/mat

**Comment by drwombat** [comment]
yes please. other services like tapped out, goldfish, manabox, deckbox, scryfall, etc - have new sets at or before release date. it's been 8 days and still no MAT in studio!?? What gives. Why always the delay - makes it impossible to build decks and catalogue cards from the set when available to buy in stores.

**Comment by dangerdoug** [comment]
Would love to see MAT added as well.  I do understand the delays as this isn't a typical cloud based program, however it is a little frustrating.  Thank you for the time you put into this and look forward to adding my MAT into MTG Studio.
