### ISSUE TITLE
All-Seeing Arbiter  / Game Day Promos GDY

### ISSUE THREAD

**Issue by xaviert00** [gaddlord/mtg.studio#515]
(https://scryfall.com/card/gdy/3/all-seeing-arbiter)

All-Seeing Arbiter
{4}{U}{U}
Creature — Avatar

Flying

Whenever All-Seeing Arbiter enters the battlefield or attacks, draw two cards, then discard a card.

Whenever you discard a card, target creature an opponent controls gets -X/-0 until your next turn, where X is the number of different mana values among cards in your graveyard.

5/4
Illustrated by [Nicholas Gregory]

**Comment by gaddlord** [comment]
All 9 GDY cards were added to forthcoming MTG Studio 3.186
