### ISSUE TITLE
Aether Channeler / Store championships

### ISSUE THREAD

**Issue by xaviert00** [gaddlord/mtg.studio#516]
https://scryfall.com/card/sch/11/aether-channeler

Aether Channeler
{2}{U}
Creature — Human Wizard

When Aether Channeler enters the battlefield, choose one —

• Create a 1/1 white Bird creature token with flying.

• Return another target nonland permanent to its owner’s hand.

• Draw a card.

2/1
Illustrated by [Olivier Bernard]

**Comment by gaddlord** [comment]
This card is available now.
