### ISSUE TITLE
Touch the Spirit Realm / Game Day promo

### ISSUE THREAD

**Issue by xaviert00** [gaddlord/mtg.studio#518]
https://scryfall.com/card/gdy/4/touch-the-spirit-realm

Touch the Spirit Realm
{2}{W}
Enchantment

When Touch the Spirit Realm enters the battlefield, exile up to one target artifact or creature until Touch the Spirit Realm leaves the battlefield.

Channel — {1}{W}, Discard Touch the Spirit Realm: Exile target artifact or creature. Return it to the battlefield under its owner’s control at the beginning of the next end step.

Illustrated by [Mila Pesic]

**Comment by gaddlord** [comment]
This card is available now.
