### ISSUE TITLE
Error message when i try to Update Prices

### ISSUE THREAD

**Issue by Amaihel** [gaddlord/mtg.studio#523]
**Describe the bug**
When i click Update Prices an error message apear
It appened after i did the update of MTG studio cause i didint used it for a long time.

**To Reproduce**
1. Go to file
2. Click on Update Prices...
3. See error

**Expected behavior**
The prices of the Market price Colone apear / get updated

**Screenshots**
![image](https://github.com/gaddlord/mtg.studio/assets/67378008/a08adb67-6eac-4ded-9495-ecd7af73c228)

Bug repport text:

date/time          : 2023-06-20, 21:58:22, 921ms
operating system   : Windows 10 x64 build 19045
system language    : French
system up time     : 5 days 6 hours
program up time    : 1 hour 20 minutes
processors         : 8x Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
physical memory    : 11980/16264 MB (free/total)
free disk space    : (C:) 307,82 GB
display mode       : 1536x864, 32 bit
process id         : $3594
allocated memory   : 268,41 MB
largest free block : 261,30 MB
executable         : mtgstudio.exe
exec. date/time    : 2023-05-27 19:29
version            : 3.182.8547.35081
compiled with      : Delphi 10.4 Sydney
madExcept version  : 5.1.1
Activation Id      : 085e10cf-7c55-11ec-a4d6-00155d935000
Registration Id    : 3ee26417-7c55-11ec-a4d6-00155d935000 for Melodie Sirois
Last Card Id       : 3664
Address            : $442826
Sender             : frmDecker.bbDeckUpdatePrices in [dxBar]
callstack crc      : $8bc3ffc4, $cf1a7e90, $cf1a7e90
count              : 3
exception number   : 2
exception class    : ESQLException
exception message  : ESQLException.

main thread ($2c7c):
004b6cb5 +35 mtgstudio.exe Sqlite.Driver      2309  +9 TSQLRequest.Close
004b7148 +a8 mtgstudio.exe Sqlite.Driver      2521 +18 TSQLRequest.Step
0057a9ec +28 mtgstudio.exe System.Data.SQLite  403  +3 TSQLiteConnection.ExecuteNonQuery
0057a32e +5e mtgstudio.exe System.Data.SQLite  267  +3 TSQLiteConnection.AttachDatabase
00a5121c +a8 mtgstudio.exe frm_Decker         8778 +14 TfrmDecker.acDeckUpdatePricesExecute
75fe6d0f +8f msvcrt.dll                                _vsnwprintf_l
7676e8a3 +43 oleaut32.dll                              SysFreeString
75e05e7b +0b USER32.dll                                DispatchMessageW
00aab6a2 +66 mtgstudio.exe unt_MtgStudio       354 +14 TMtgStudio.Run
758700c7 +17 KERNEL32.DLL                              BaseThreadInitThunk

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 pro
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 114.0.5735.134 (Build officiel) (64 bits)

———
Upvote my bug report be pressing 👍 from the 😊 menu.

**Comment by texasaggie1994** [comment]
Same error here.

**Comment by drwombat** [comment]
same error here.

![update](https://github.com/gaddlord/mtg.studio/assets/110059020/be10bddb-8e05-4bad-93e0-9477bcb16bf9)

**Comment by Plutaneous** [comment]
Same error here as well.

**Comment by drwombat** [comment]
Hi @gaddlord it's been several months and pricing is still broken and showing this error. Any update on teh fix?
Thanks!

**Comment by gaddlord** [comment]
This is fixed in the latest MTG Studio 3.187. The TCG Player prices API had been deprecated. I switched to the new API in the latest version. Should be fixed now.
