### ISSUE TITLE
Is anyone still working on this project??

### ISSUE THREAD

**Issue by drwombat** [gaddlord/mtg.studio#526]
It's been weeks since the release of LTR/LTC an no card updates, no progress on the issues, etc. Status page hasn't seen an updated status since May. Has this program been abandoned?!?

**Comment by spieiga** [comment]
It takes some time

**Comment by drwombat** [comment]
Ok but it's extremely frustrating to pay for a product and then not have it be accurate/complete. Scryfall is awash in CMM cards, and Studio doesn't even have the prior set yet. LTR/LTC came out a month ago and card lists were available well before then. Not being able to catalog any of the new cards or build decks with them in Studio makes the product worthless until it's updated. Not cool when you charge people money for the program.

**Comment by skarsol** [comment]
CCM is complete now (https://github.com/gaddlord/mtg.studio/issues/530) and WOE and WHO cards are starting to show up now.

**Comment by skarsol** [comment]
I guess we just try to find a different program that can accept an MTG Studio export now?

**Comment by gaddlord** [comment]
LTR and HA7 were added. Working on LTR Commander and CMM tonight. WOE and WHO we would add once the sets are complete.

**Comment by drwombat** [comment]
Excellent - also thanks for the email you sent me the other day about the cause of your delays. I appreciated that.
