### ISSUE TITLE
[Missing Cards] - The List 

### ISSUE THREAD

**Issue by BarrelRider91** [gaddlord/mtg.studio#528]
https://scryfall.com/card/plist/786/old-gnawbone
https://scryfall.com/card/plist/1011/sword-of-feast-and-famine
https://scryfall.com/card/plist/1003/mycosynth-lattice
https://scryfall.com/card/plist/523/graveborn-muse

**Comment by gaddlord** [comment]
Version 3.186 comes will all upto date 1288 The List cards.
