### ISSUE TITLE
[Missing Card] Skyclave Apparition / Game Day Promos GDY # 002

### ISSUE THREAD

**Issue by xaviert00** [gaddlord/mtg.studio#531]
(https://scryfall.com/card/gdy/2/skyclave-apparition)

Skyclave Apparition
{1}{W}{W}
Creature — Kor Spirit

When Skyclave Apparition enters the battlefield, exile up to one target nonland, nontoken permanent you don’t control with mana value 4 or less.

When Skyclave Apparition leaves the battlefield, the exiled card’s owner creates an X/X blue Illusion creature token, where X is the mana value of the exiled card.

2/2
Illustrated by [Mila Pesic]

**Comment by gaddlord** [comment]
All 9 GDY cards were added to forthcoming MTG Studio 3.186
