### ISSUE TITLE
[Missing Card] Strangle (store championship)

### ISSUE THREAD

**Issue by xaviert00** [gaddlord/mtg.studio#532]
(https://scryfall.com/card/sch/10/strangle)

Strangle
{R}
Sorcery

Strangle deals 3 damage to target creature or planeswalker.

Illustrated by [Sidharth Chaturvedi]

Standard
LEGAL
Alchemy
LEGAL
Pioneer
LEGAL
Explorer
LEGAL
Modern
LEGAL
Brawl
LEGAL
Legacy
LEGAL
Historic
LEGAL
Vintage
LEGAL
Pauper
LEGAL
Commander
LEGAL
Penny
LEGAL
Oathbreaker
LEGAL

**Comment by gaddlord** [comment]
This card is available now.
