### ISSUE TITLE
braids, arisen nightmare  (game day  GDY 008)

### ISSUE THREAD

**Issue by xaviert00** [gaddlord/mtg.studio#533]
(https://scryfall.com/card/gdy/8/braids-arisen-nightmare)

Braids, Arisen Nightmare
{1}{B}{B}
Legendary Creature — Nightmare

At the beginning of your end step, you may sacrifice an artifact, creature, enchantment, land, or planeswalker. If you do, each opponent may sacrifice a permanent that shares a card type with it. For each opponent who doesn’t, that player loses 2 life and you draw a card.

3/3
Illustrated by [Anastasia Balakchina]

Standard
LEGAL
Alchemy
LEGAL
Pioneer
LEGAL
Explorer
LEGAL
Modern
LEGAL
Brawl
LEGAL
Legacy
LEGAL
Historic
LEGAL
Vintage
LEGAL
Pauper
NOT LEGAL
Commander
LEGAL
Penny
NOT LEGAL
Oathbreaker

**Comment by gaddlord** [comment]
All 9 GDY cards were added to forthcoming MTG Studio 3.186
