### ISSUE TITLE
[Missing Card] Recruitment officer (game day  GDY 007)

### ISSUE THREAD

**Issue by xaviert00** [gaddlord/mtg.studio#534]
(https://scryfall.com/card/gdy/7/recruitment-officer)

Recruitment Officer
{W}
Creature — Human Soldier

{3}{W}: Look at the top four cards of your library. You may reveal a creature card with mana value 3 or less from among them and put it into your hand. Put the rest on the bottom of your library in a random order.

2/1
Illustrated by [Zoltan Boros]

Standard
LEGAL
Alchemy
LEGAL
Pioneer
LEGAL
Explorer
LEGAL
Modern
LEGAL
Brawl
LEGAL
Legacy
LEGAL
Historic
LEGAL
Vintage
LEGAL
Pauper
NOT LEGAL
Commander
LEGAL
Penny
LEGAL
Oathbreaker

**Comment by gaddlord** [comment]
All 9 GDY cards were added to forthcoming MTG Studio 3.186
