### ISSUE TITLE
[Missing Card] workshop warchief (game day  GDY 005)

### ISSUE THREAD

**Issue by xaviert00** [gaddlord/mtg.studio#535]
(https://scryfall.com/card/gdy/5/workshop-warchief)

Workshop Warchief
{3}{G}{G}
Creature — Rhino Warrior

Trample

When Workshop Warchief enters the battlefield, you gain 3 life.

When Workshop Warchief dies, create a 4/4 green Rhino Warrior creature token.

Blitz {4}{G}{G} (If you cast this spell for its blitz cost, it gains haste and “When this creature dies, draw a card.” Sacrifice it at the beginning of the next end step.)

5/3
Illustrated by [Maxime Minard]

Standard
LEGAL
Alchemy
LEGAL
Pioneer
LEGAL
Explorer
LEGAL
Modern
LEGAL
Brawl
LEGAL
Legacy
LEGAL
Historic
LEGAL
Vintage
LEGAL
Pauper
NOT LEGAL
Commander
LEGAL
Penny
LEGAL
Oathbreaker

**Comment by gaddlord** [comment]
All 9 GDY cards were added to forthcoming MTG Studio 3.186
