### ISSUE TITLE
[Missing Card] vorinclex, monstrous raider (concept praetor 406)

### ISSUE THREAD

**Issue by xaviert00** [gaddlord/mtg.studio#536]
(https://scryfall.com/card/khm/406/vorinclex-monstrous-raider)

orinclex, Monstrous Raider
{4}{G}{G}
Legendary Creature — Phyrexian Praetor

Trample, haste

If you would put one or more counters on a permanent or player, put twice that many of each of those kinds of counters on that permanent or player instead.

If an opponent would put one or more counters on a permanent or player, they put half that many of each of those kinds of counters on that permanent or player instead, rounded down.

6/6
Illustrated by [Richard Whitters]

Standard
NOT LEGAL
Alchemy
NOT LEGAL
Pioneer
LEGAL
Explorer
LEGAL
Modern
LEGAL
Brawl
NOT LEGAL
Legacy
LEGAL
Historic
LEGAL
Vintage
LEGAL
Pauper
NOT LEGAL
Commander
LEGAL
Penny
NOT LEGAL
Oathbreaker

**Comment by gaddlord** [comment]
There are 2 of them. The second one is Collector No: 407 https://scryfall.com/card/khm/407/vorinclex-monstrous-raider
Both (406 M Special Praetor and 407 M Special Praetor) were added in the forthcoming MTG Studio 3.194 release.
