### ISSUE TITLE
[Missing Card] Memory Deluge (store championship  SCH 008)

### ISSUE THREAD

**Issue by xaviert00** [gaddlord/mtg.studio#537]
(https://scryfall.com/card/sch/8/memory-deluge)

Memory Deluge
{2}{U}{U}
Instant

Look at the top X cards of your library, where X is the amount of mana spent to cast this spell. Put two of them into your hand and the rest on the bottom of your library in a random order.

Flashback {5}{U}{U} (You may cast this card from your graveyard for its flashback cost. Then exile it.)

Illustrated by [Sam Guay]

Standard
LEGAL
Alchemy
LEGAL
Pioneer
LEGAL
Explorer
LEGAL
Modern
LEGAL
Brawl
LEGAL
Legacy
LEGAL
Historic
LEGAL
Vintage
LEGAL
Pauper
NOT LEGAL
Commander
LEGAL
Penny
NOT LEGAL
Oathbreaker

**Comment by gaddlord** [comment]
This card is available now.
