### ISSUE TITLE
[Missing Card] Shivan Devastator (game day GDY 006)

### ISSUE THREAD

**Issue by xaviert00** [gaddlord/mtg.studio#538]
(https://scryfall.com/card/gdy/6/shivan-devastator)

Shivan Devastator
{X}{R}
Creature — Dragon Hydra

Flying, haste

Shivan Devastator enters the battlefield with X +1/+1 counters on it.

0/0
Illustrated by [Aldo Domínguez]

Standard
LEGAL
Alchemy
LEGAL
Pioneer
LEGAL
Explorer
LEGAL
Modern
LEGAL
Brawl
LEGAL
Legacy
LEGAL
Historic
LEGAL
Vintage
LEGAL
Pauper
NOT LEGAL
Commander
LEGAL
Penny
NOT LEGAL
Oathbreaker
LEGAL

**Comment by gaddlord** [comment]
All 9 GDY cards were added to forthcoming MTG Studio 3.186
