### ISSUE TITLE
Missing card price info - still

### ISSUE THREAD

**Issue by drwombat** [gaddlord/mtg.studio#542]
Pricing at card image no longer works, and hasn't for several updates. 
See arrow below - this whole section has been blank for a while now.

![pic](https://github.com/gaddlord/mtg.studio/assets/110059020/a000c101-b4ce-4652-88f5-504506d4aeb1)

**Comment by Amaihel** [comment]
Error message when i try to Update Prices #523

It goes with the issue i mentionned...
It say it's resolved but i still have the prob..

![image](https://github.com/gaddlord/mtg.studio/assets/67378008/ea61efe0-f029-4f2f-9908-3cd34178b1bd)

**Comment by drwombat** [comment]
TCG pricing in the card window appears to be back. But it's wrong. TCG Market is NOT showing up under the card window, and the prices imported into the collection are INCORRECT. See attached images.
![tcg missing](https://github.com/gaddlord/mtg.studio/assets/110059020/6693be90-1faf-4ba6-9487-2ffe9c604de8)
![tcg incorrect](https://github.com/gaddlord/mtg.studio/assets/110059020/56c04490-d14d-41f1-ae01-bd1c59b88c6e)

**Comment by Amaihel** [comment]
Soon been a year that we reported the bug and still no update...
If you don care about fixing it can you just tell us at last plz...?

**Comment by gaddlord** [comment]
I believe this is fixed a few versions back.

**Comment by Amaihel** [comment]
no, it's not, that's why i keep asking for update

You've closed the issue twice and the problem still exist

If you don't care about it and don't want to fix it, just say it
If it's really fixed then tell me why it still dosent work for me 

![image](https://github.com/user-attachments/assets/386e9e2e-9a37-4daf-b78a-76441a7018eb)

ty

**Comment by gaddlord** [comment]
Interesting. The error behid the scene is "exception message : file is not a database."
I am quite curious to understand how it reached that state. I am assuming your mtgstudio.prices file was partially donwloaded and broken by perhaps disconnected Internet while downloading back in time.

**Can you please delete (it is a safe operation) your mtgstudio.prices file in your Configuration folder?** Information on where Configuration folder is available at https://github.com/gaddlord/mtg.studio/wiki/Directory-Structure

It is the cache of downloaded prices.
It will be recreated the next time you select File | Import | Prices.

In case you need assistance let me know and I can organize a quick shared screen troubleshooting session.

**Comment by Amaihel** [comment]
I deleted the mtgstudio.prices file in your Configuration folder like asked but it still give me an error when i try tho import the prices 

any other idea?

![image](https://github.com/user-attachments/assets/379f3b9d-d8e6-46b3-8c59-132c114c05a6)
![image](https://github.com/user-attachments/assets/6f281e9b-f52b-48fe-8ee0-4d7367af8eaf)

**Comment by Amaihel** [comment]
If you think it would work, maybe just reinstal everything? 

Visibly something isin't right with my MTG...

**Comment by gaddlord** [comment]
Can you 
1. Stop MTG Studio
2. unzip the file tcgplayer.prices in your Configuration folder and overwrite the file with the one from the ZIP?
[tcgplayer.zip](https://github.com/user-attachments/files/18246700/tcgplayer.zip)
3. Start MTG Studio and try File | Update Prices.

**Comment by Amaihel** [comment]
same résult :/

**Comment by gaddlord** [comment]
Are you OK we have a shared screen session on Discord so I can try to troubleshoot it?

**Comment by Amaihel** [comment]
sure, no problem ^^
how do we do?

**Comment by gaddlord** [comment]
Can you join our Discord server at https://discord.gg/VZGV8CGA and write in the General channel. My username there is "mtg.studio creator"

**Comment by gaddlord** [comment]
The problem was resolved by deleting the mtgstudio.conf file (or single setting with Key=''prices").
