### ISSUE TITLE
two wrong images 

### ISSUE THREAD

**Issue by xaviert00** [gaddlord/mtg.studio#561]
the following two card are showing the wrong image .. both are showing the image of their variant 

Gaea's Touch  (The dark)
the correct picture is below the text is properly centered in the box
https://scryfall.com/card/drk/77/gaeas-touch

Runesword (The dark) 
the correct picture is below and doe snot have a hair showing
https://scryfall.com/card/drk/107/runesword

**Comment by gaddlord** [comment]
Runesword updated with the Scryfall picture (without hair).

**Comment by gaddlord** [comment]
Updated the Gaea's Touch card art to have the card name correctly offseted.
Please note that in order to see the changes one must remove the local Card Art cache.
