### ISSUE TITLE
LCI Art not loading

### ISSUE THREAD

**Issue by drwombat** [gaddlord/mtg.studio#566]
hi in the latest release from today Nov 13 2023, none of the art for LCI cards loads. regular/other sets load as normal:

![image](https://github.com/gaddlord/mtg.studio/assets/110059020/fa459d13-218b-4747-980e-bbe13cae56ba)

**Comment by drwombat** [comment]
I looked at this further. The files the program is creating (xyzartwork.full.jpg) are corrupted jpg files. They will not open in any image generator for new files. Existing downloaded xyz.full.jpg files work just fine. I manually replaced a file for an LCI card with a known working jpg and named it accordingly and it worked. please fix. thanks!

**Comment by drwombat** [comment]
This appears to be fixed in the latest update thank you

**Comment by gaddlord** [comment]
Yep, In case you have doubts that your locally cached images are partially downloaded or broken, just delete the image or the whole Card Art folder. It is a safe operation since MTG Studio redownloads the most recent card art once you select a card.
