### ISSUE TITLE
All SPG cards from LCI

### ISSUE THREAD

**Issue by nomojomo** [gaddlord/mtg.studio#569]
Example. There are 13 cards in total, most with multiple prints, including 7 of mana crypt

Card Image Link: https://cards.scryfall.io/large/front/3/d/3d5073a2-4839-4f33-bda4-6f0a98d3739b.jpg?1698988670
Name: Lord of Atlantis
Foreign Name: Centauro Piesligeros
Set: LCI
Sub-Set: SPG

**Comment by gaddlord** [comment]
The link to the set is https://scryfall.com/sets/spg
I will be adding it to 3.194

**Comment by nomojomo** [comment]
Awesome!

**Comment by gaddlord** [comment]
24 cards were added to forthcoming 3.914 release.
