### ISSUE TITLE
Project presumed to be abandoned

### ISSUE THREAD

**Issue by drwombat** [gaddlord/mtg.studio#585]
Website has expired.
No action on this github page since March 2024.
No OTJ/etc cards added, release was 2 weeks ago, 3 counting prerelease, and more counting full card spoilers.

We paid real money for this program. Either do your part and keep this program updated for your PAYING customers or just admit you're done, close up, and stop wasting our time.

Thank you

**Comment by nomojomo** [comment]
Agree with drwombat... and feel it would be nice to hear from the developer, one way or another.

**Comment by nomojomo** [comment]
Hi. I have version 3.203.0.0, last updated sometime in March, 2024. No update is reported available.

I have Fallout cards in the card pool, but none of the other sets ( OTJ, OTB, OTC, MH3, M3C ) listed in your July 14 update for version 3.203.0.0. 

Is there possibly a version number
![MTGS20240801](https://github.com/user-attachments/assets/3dd83168-b4eb-42d8-8a39-770bcc084c9d)
 collision issue?

**Comment by texasaggie1994** [comment]
Release 3.204 was released Aug 19.

**Comment by gaddlord** [comment]
We are alive and kicking. Indeed I have been not active recent few months (due to personal reasons). I am back in and plan adding somre more cards.
