### ISSUE TITLE
Discrepancy between GitHub and official MTG Studio websites

### ISSUE THREAD

**Issue by Revilak** [gaddlord/mtg.studio#589]
Hi Gaddlord,

I'm just a bit confused because on MTG Studio Github webpage  https://github.com/gaddlord/mtg.studio/wiki/Previous-Versions   I see

![MTG Studio Github](https://github.com/user-attachments/assets/d6bb7b3f-2450-4654-9c54-020b16c1f631)

But on official MTG Studio website  https://mtg.studio/      When hovering on download button  I see

![MTG Studio Official (1)](https://github.com/user-attachments/assets/ae68e175-7d05-499a-90ea-3573dd8a0c36)

And further down on the same webpage 

![MTG Studio Official (2)](https://github.com/user-attachments/assets/db429cc0-6cb0-4de6-ba1d-1fae2b6c7e18)

Also on MTG Studio official download page

![MTG Studio Official (3)](https://github.com/user-attachments/assets/870e27db-9572-48e5-ad95-316d7950534b)

**Comment by gaddlord** [comment]
Indeed those are ommisions. All 3 are resolved for the next version of MTG Studio 3.206.

Fixed tooltip:
![image](https://github.com/user-attachments/assets/94660464-8683-4cb4-a017-3ab74dae1aaf)

Update What I'm getting section:
![image](https://github.com/user-attachments/assets/4db37e37-f071-4cac-8c42-0b9626f280cb)

Removed the Registration section.

Updated price and Registration wiki page as well:
<img width="768" alt="image" src="https://github.com/user-attachments/assets/225dc5a5-2569-4bbc-91cf-7220ee03240e">
