### ISSUE TITLE
Version History link in installer points to old forum site

### ISSUE THREAD

**Issue by texasaggie1994** [gaddlord/mtg.studio#775]
When clicking on the version history link, you are directed to the old phpbb forum site, not the new link: https://github.com/gaddlord/mtg.studio/wiki/Version-History

**To Reproduce**
1. Start an upgrade until the install dialog comes up
2. Click on the version history link on the bottom.

**Expected behavior**
Redirect to new github version history page.

**Comment by gaddlord** [comment]
Which is the version (the one you are upgrading from), please?

**Comment by texasaggie1994** [comment]
It was 3 versions back. I saw a note in the version history one version back that you may have fixed it already. Will check with the next release.
