### ISSUE TITLE
Commander 2018 & 2019 Cards have wrong/missing collector number

### ISSUE THREAD

**Issue by texasaggie1994** [gaddlord/mtg.studio#777]
Following 4 cards have the wrong collector number in the database for Commander 2018

Dimir Signet (shows 22 but should be 203)
Dimir Aqueduct (shows 23 but should be 242)
Golgari Rot Farm (shows 74 but should be 249)
Telling Time (shows 4 but should be 105)

The following cards are missing collector number for Commander 2019

Refuse // Cooperate (this also has extra spaces in the name)
Dusk // Dawn
Farm // Market

**Comment by gaddlord** [comment]
Thanks for reporting.

Fixed the card art, rarity and collector number of:
* Dimir Signet (shows 22 but should be 203)
* Dimir Aqueduct (shows 23 but should be 242)
* Golgari Rot Farm (shows 74 but should be 249)
* Telling Time (shows 4 but should be 105)

**Comment by gaddlord** [comment]
Added Collector No for:
* Refuse // Cooperate (this also has extra spaces in the name)
* Dusk // Dawn
* Farm // Market
