### ISSUE TITLE
Latest version 3.213 not importing or updating prices

### ISSUE THREAD

**Issue by pritaeas** [gaddlord/mtg.studio#780]
When importing or updating prices an ESQLException occurs. See attached screenshot, Running on Win11.

![MTG Studio ESQLException](https://github.com/user-attachments/assets/8a4287fc-0ea4-4a34-b915-f4bc746dc3a2)

**Comment by texasaggie1994** [comment]
Confirmed as well - v3.213

**Comment by gaddlord** [comment]
I was able to reproduce it and fix it in 3.214. Will release 3.214 in a few hours. Thanks for reporting it.
