### ISSUE TITLE
Clicking "buy" in the grid fails with "no such column: sCardId" error in PriceForm.tiShowGrid in [Vcl.ExtCtrls]

### ISSUE THREAD

**Issue by texasaggie1994** [gaddlord/mtg.studio#786]
**Describe the bug**
When clicking the small button in the grid of your collection for a card for buy that pops up a list from various sellers, the window opens but I immediately get an error: "no such column: sCardId" in PriceForm.tiShowGrid in [Vcl.ExtCtrls]

**To Reproduce**
1. Go to Card Collection
2. Click on the buy... in any row
3. See error

**Screenshots**
![image](https://github.com/user-attachments/assets/14b23b73-9628-4699-90df-f4eaa9baa37d)

**Environment**

date/time          : 2024-12-21, 07:21:42, 851ms
operating system   : Windows 11 x64 build 26100
system language    : English
system up time     : 10 days
program up time    : 1 minute 33 seconds
processors         : 16x AMD Ryzen 7 7700X 8-Core Processor
physical memory    : 11301/31839 MB (free/total)
free disk space    : (C:) 776.56 GB
display mode       : 1920x1080, 32 bit
process id         : $3ea7c
allocated memory   : 424.19 MB
largest free block : 1.96 GB
executable         : mtgstudio.exe
exec. date/time    : 2024-12-19 14:31
version            : 3.215.9119.26134
compiled with      : Delphi 12
madExcept version  : 5.1.5
Address            : $48F912
Sender             : PriceForm.tiShowGrid in [Vcl.ExtCtrls]
callstack crc      : $b07274b2, $1c7a465e, $1c7a465e
exception number   : 2
exception class    : ESQLException
exception message  : no such column: sCardId.

main thread ($3de08):
00f00eea +026 mtgstudio.exe sqlite.driver         2695  +4 sqlite3_check
00f00af6 +07e mtgstudio.exe sqlite.driver         2610  +9 TSQLRequest.Prepare
00fc2e87 +09b mtgstudio.exe sqlite.mormot.helper   225  +7 TSQLiteConnection.BindStatement
00fc34b4 +008 mtgstudio.exe sqlite.mormot.helper   346  +2 TSQLiteConnection.GetDataReader
013e07c8 +060 mtgstudio.exe mtgstudio.database    2175  +3 TMtgStudioDatabase.GetTcgPlayerPriceInput
01d7bd0d +049 mtgstudio.exe price.vcl.form         231  +2 TPriceForm.acRefreshPricesExecute
005582df +00f mtgstudio.exe System.Classes                 TBasicAction.Execute
005cbc4a +086 mtgstudio.exe Vcl.ActnList                   TCustomAction.Execute
01d7d44f +01b mtgstudio.exe price.vcl.form         700  +3 TPriceForm.tiShowGridTimer
0069ca43 +00f mtgstudio.exe Vcl.ExtCtrls                   TTimer.Timer
0069c923 +02b mtgstudio.exe Vcl.ExtCtrls                   TTimer.WndProc
00559110 +014 mtgstudio.exe System.Classes                 StdWndProc
759d4b1b +00b USER32.dll                                   DispatchMessageW
00713e5b +0f3 mtgstudio.exe Vcl.Forms                      TApplication.ProcessMessage
00713e9e +00a mtgstudio.exe Vcl.Forms                      TApplication.HandleMessage
0070ee95 +27d mtgstudio.exe Vcl.Forms                      TCustomForm.ShowModal
01d7d2b9 +125 mtgstudio.exe price.vcl.form         678 +14 TPriceForm.ShowDialog
0202da27 +23f mtgstudio.exe main.vcl.form        11371 +22 TMainForm.btvCollectionBuyAtPropertiesButtonClick
00b75d54 +05c mtgstudio.exe cxEdit               10827  +8 TcxCustomEdit.DoButtonClick
00b76920 +06c mtgstudio.exe cxEdit               11153  +8 TcxCustomEdit.DoProcessEventsOnViewInfoChanging
00a010ab +02f mtgstudio.exe cxContainer           5267  +5 TcxContainer.ProcessEventsOnViewInfoChanging
00a0059d +09d mtgstudio.exe cxContainer           4989 +14 TcxContainer.RefreshContainer
009ff2f1 +051 mtgstudio.exe cxContainer           4333  +3 TcxContainer.MouseUp
00cd5918 +014 mtgstudio.exe cxMaskEdit            2874  +1 TcxCustomMaskEdit.MouseUp
005f0498 +034 mtgstudio.exe Vcl.Controls                   TControl.DoMouseUp
005f0526 +082 mtgstudio.exe Vcl.Controls                   TControl.WMLButtonUp
005efb0e +2be mtgstudio.exe Vcl.Controls                   TControl.WndProc
005f51c3 +6a7 mtgstudio.exe Vcl.Controls                   TWinControl.WndProc
00a83dc4 +200 mtgstudio.exe cxControls           10672 +25 TcxControl.WndProc
00a83ea5 +2e1 mtgstudio.exe cxControls           10701 +54 TcxControl.WndProc
009ff744 +0a0 mtgstudio.exe cxContainer           4515 +25 TcxContainer.WndProc
00cbe52c +124 mtgstudio.exe cxTextEdit            6339 +23 TcxCustomTextEdit.WndProc
005f4688 +02c mtgstudio.exe Vcl.Controls                   TWinControl.MainWndProc
005f46a3 +047 mtgstudio.exe Vcl.Controls                   TWinControl.MainWndProc
00559110 +014 mtgstudio.exe System.Classes                 StdWndProc
759d4b1b +00b USER32.dll                                   DispatchMessageW
00713e5b +0f3 mtgstudio.exe Vcl.Forms                      TApplication.ProcessMessage
00713e9e +00a mtgstudio.exe Vcl.Forms                      TApplication.HandleMessage
007141dd +0d1 mtgstudio.exe Vcl.Forms                      TApplication.Run
021bd0a5 +0a1 mtgstudio.exe mtgstudio.vcl.app      259 +26 TMtgStudio.Run
75f35d47 +017 KERNEL32.DLL                                 BaseThreadInitThunk

**Comment by gaddlord** [comment]
Hello,

Thanks for reporting. This is fixed in the latest 3.216 version.

Gad

**Comment by gaddlord** [comment]
Fixed in 3.216
